
name: Lazy Kernel Builder

on:
  push:

jobs:
  super-job:
    runs-on: ubuntu-20.04

    env:
      CACHE_DIR: ~/.cache

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            flex bison ncurses-dev texinfo gcc gperf patch \
            libtool automake g++ libncurses5-dev gawk subversion \
            expat libexpat1-dev python-all-dev binutils-dev bc \
            libcap-dev autoconf libgmp-dev build-essential \
            pkg-config libmpc-dev libmpfr-dev autopoint gettext \
            txt2man liblzma-dev libssl-dev libz-dev mercurial \
            wget tar gcc-10 g++-10 cmake zstd ninja-build lz4 \
            liblz4-tool liblz4-dev lzma --fix-broken --fix-missing
