
name: Lazy Kernel Builder

on:
  push:

jobs:
  super-job:
    runs-on: ubuntu-20.04

    env:
      CACHE_DIR: ~/.cache

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          uname -r;lscpu;pwd;id
